### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by jamie-portman** [bstroebl/DigitizingTools#16]
We love this plugin and many of the tools it brings to QGIS. 
We do however seem to often have issues when we have it turned on, with saving edits progressively running slower and slower (literally locking up QGIS for 15mins+). A shut down of QGIS temporarily resolves the issue but it does start again. Turning the plugin off when not in use resolves the issue. Through a process of elimination, we have isolated this plugin as the cause.
Could it be some kind of memory leak issue that could be resolved?
Current version of the plugin is being used with the LTR release, v2.14.5.

**Comment by bstroebl** [comment]
This is normally the cause if layers are connected to the start/stop editing signals and get reconnected all the time, thus the same slot is run many (really many) times. It is known that there are plugins around that run into this problem, however DigitizingTools is not. It used to many months ago, though, so please make double sure you are running the current version.
Please do unload all(!) other plugins and then go ahead digitizing. If the behaviour persists I would be glad if you could share your data.

**Comment by bstroebl** [comment]
closing this diue to lack of feedback
