### ISSUE TITLE
Split Feature for multigeometries with control of result

### ISSUE THREAD

**Issue by bstroebl** [bstroebl/DigitizingTools#19]
QGIS' _Split parts_ tool currently results in an invalid geometry as both newly created parts stay within the multi-part feature. Any further splitting results in a geometry error. If QGIS' _Split feature_ is applied on a part of a multi-part feature, both geometries (let's call them _halves_) of the former part become new features.
The proposed tool should act like QGIS' native tools but after splitting offers the user to choose which of the halves should become the new feature and which is to stay as part within the original feature.

**Comment by andywicht** [comment]
+1 for that.
It has to be ensured that disjoint parts are not separated into a third feature (current _split feature_ does that). The result should in any case always be 2 (multipart) features.

**Comment by bstroebl** [comment]
Implemented in version 0.11.0
