### ISSUE TITLE
Enhancement: Delete last digitized node of blade geometry in Split Features tool

### ISSUE THREAD

**Issue by andywicht** [bstroebl/DigitizingTools#21]
The core tools have the very useful functionality to delete the latest digitized node of the blade geometry by hitting backspace.
When doing this with the Split Features tool, the default behaviour kicks in and the selected feature gets deleted.

This is particularly helpful when digitizing long blade geometries in order not to repeat the process in case some node were not digitized correctly.

**Comment by bstroebl** [comment]
I was not aware of this feature, thank you for pointing it out; I mark this as enhancement

**Comment by bstroebl** [comment]
Will be realised fro QGIS 3

**Comment by bstroebl** [comment]
implemented for QGIS3 in 1c03a5fb59451de793f4ed65a6675899351a7779
