### ISSUE TITLE
Bug: Invalid blade geometry freezes QGIS for MultiPolygon Features

### ISSUE THREAD

**Issue by andywicht** [bstroebl/DigitizingTools#22]
In case an invalid blade geometry is digitised (no closed part available to cut from the original geometry) when the selected feature is of type "MultiPolygon" (does not matter if there actually are parts or not), QGIS will freeze irrecoverably. 

![invalid_blade_geom](https://user-images.githubusercontent.com/21099522/27380191-7c1f8c74-567e-11e7-8785-3d09e911a54c.png)

This can for example happen when a user accidentally hits the right mouse button while digitising a blade geometry.

Can not reproduce this behaviour with geometry type "Polygon". In that case the action is simply cancelled. This behaviour is desirable to be implemented for MultiPolygon features as well.

QGIS Version: 2.18.9

**Comment by bstroebl** [comment]
New Version of the plugin is available on QGIS' plugin site
