### ISSUE TITLE
Bring back Amend line

### ISSUE THREAD

**Issue by PietsHost** [bstroebl/DigitizingTools#23]
Amend line - removed in Version 0.11.0 (QGIS 2.16+)

Please bring that feature back to DigitizingTools. It's very important for us and we do need that Feature.

Thanks!

**Comment by bstroebl** [comment]
Hi,
glad that you liked it, however it was removed to avoid redundant functions because QGIS' _Reshape Features_ does exactly the same. Could you explain where the _Amend line_ tool is any different from _Reshape Features_.

**Comment by PietsHost** [comment]
Reshape Feature? Could you explain, where I do find this function?

**Comment by bstroebl** [comment]
It's in the _Advanced Digitizing Toolbar_.

**Comment by PietsHost** [comment]
Well, I can modify a Line, but I can't expand it.. see here:

http://recordit.co/Shvuh8tY6c

**Comment by bstroebl** [comment]
Link does not work here (probably a proxy problem), anywys: 
1. enable snapping for the layer in question
2. aktivate _Reshape Features_ tool
3. click to either of the line's endpoints (you see it highlighted when within snap distance)
4. continue clicking for more vertices
see [manual](http://docs.qgis.org/2.18/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#reshape-features)

**Comment by bstroebl** [comment]
Please close this issue if _Reshape Features_ works for you or specify differences to _Amend line_

**Comment by PietsHost** [comment]
I guess you don't understand what I want to do.. I just want to _extend_ a line... With the Reshape Tool i can _modify_ it....
Here's the Line I want to extend:
![screenshot_15](https://user-images.githubusercontent.com/3725416/30028199-6ab5285e-9184-11e7-8d45-b1c59a598e13.png)

my expeted result should be this (adding the black part):
![screenshot_15](https://user-images.githubusercontent.com/3725416/30028235-884a1f96-9184-11e7-84e3-cde00e3d3b60.png)

now, using the Reshape Tool:
![screenshot_16](https://user-images.githubusercontent.com/3725416/30028244-9213cb8a-9184-11e7-8e1c-38ea7aab4ca3.png)

the result is:
![screenshot_17](https://user-images.githubusercontent.com/3725416/30028254-96714f72-9184-11e7-9c1e-8c77a4e4e250.png)

**Comment by PietsHost** [comment]
and with "add Part" --> 
![screenshot_18](https://user-images.githubusercontent.com/3725416/30028358-0781a1b2-9185-11e7-914b-d59c176ca8ba.png)

I get this:
![screenshot_19](https://user-images.githubusercontent.com/3725416/30028365-0b320356-9185-11e7-9838-c3a8627b8d00.png)

**Comment by bstroebl** [comment]
I do understand what you want to achieve, I know what the _Amend line_ tool used to do. 
Have you followed my instructions and/or read the manual? Your drawing does suggest that you did not click at the line's endpoint. The manual contains a tip _Extend linestring geometries with reshape tool_.
_Add part_ is for multi-part features which is something completely different.

**Comment by PietsHost** [comment]
yea I know and I did read the manual. The problem is: If i try to click the line's endpoint, nothing is selected.. Instead it starts drawing

**Comment by PietsHost** [comment]
![screenshot_20](https://user-images.githubusercontent.com/3725416/30028640-24f0ec20-9186-11e7-9b82-619220877cff.png)
Here I tried to click the line's endpoint with Reshape Tool enabled.. It's just 1 click on the "x" (endpoint) and a second click a few cm away.. doesn't work and the endpoint isn't selected

**Comment by bstroebl** [comment]
Is snapping enabled for the layer?

Here is my line:
![line1](https://user-images.githubusercontent.com/2534601/30029181-7e715634-9188-11e7-8e82-d137b592837f.png)

mouse cursor is not visible but you can see the endpoint being highlighted as snap point when the mouse is within snap distance
![line2](https://user-images.githubusercontent.com/2534601/30029184-825e8492-9188-11e7-9923-ff775b57269a.png)

click to catch the snappoint and amend the line with further clicks
![line3](https://user-images.githubusercontent.com/2534601/30029186-85089160-9188-11e7-8614-3de9126c7a67.png)

line finished (not saved yet)
![line4](https://user-images.githubusercontent.com/2534601/30029187-876b6b1c-9188-11e7-95d8-5608019ae676.png)

this is in QGIS 2.18.12 on Linux

**Comment by PietsHost** [comment]
oh wow.. mal kurz auf Deutsch:

Ich habe die Einstellungen für's "Snapping" aka "Objektfang" nicht gefunden.. Hat so aber tatsächlich funktioniert. Besten Dank!

**Comment by bstroebl** [comment]
Gut, aber Fangen mußte auch für _Amend line_ in DigitizingTools eingestellt sein, soweit ich mich erinnere, sonst wurde auch kein Endpunkt gefangen.

**Comment by PietsHost** [comment]
Ne, eben nicht. Für _Amend line_ ging's out-of-the-box ;)

**Comment by bstroebl** [comment]
Na, aber er muß doch wissen, an welche Linie er ansnappen soll, im Code ist jedenfalls was mit snapping drin. Vielleicht hattest Du das Snapping auch defaultmässig für den aktuellen Layer an?
Ist ja auch egal, jetzt geht es jedenfalls.
