### ISSUE TITLE
Clipping tool for polygons in one layer

### ISSUE THREAD

**Issue by stamogis** [bstroebl/DigitizingTools#25]
Enhanced proposal:
I want to intersect two overlaying surfaces within one layer. The cutting polygon is to be stamped out in the bottom polygon (hole, donut). The cutting polygon must be retained. 
A concrete scenario would be for example: I have a green area on which a new tree is planted. This new plantation receives a (round) tree disc. The polygon of the tree disc is digitized at the future position. The area of the tree disc must be cut out of the green area, but the area of the tree disc must be preserved. Both polgons are in the same layer.
The name of the new function could be "cut", "cut and paste", "clip" or "exclude", for example.

**Comment by bstroebl** [comment]
Realized in Version 1.1.0
