### ISSUE TITLE
DigitizingTools not working for QGIS 3.0.2 Girona

### ISSUE THREAD

**Issue by Francescocardia** [bstroebl/DigitizingTools#26]
Here is the error message

Impossibile caricare il plugin 'DigitizingTools' a causa di un errore chiamando il metodo classFactory() 

ModuleNotFoundError: No module named 'digitizingtools' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/francesco.cardia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\DigitizingTools\__init__.py", line 26, in classFactory
    from digitizingtools import DigitizingTools
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'digitizingtools'

Versione Python: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
Versione di QGIS: 3.0.2-Girona Girona, 307d082e3d 

Percorso Python:
C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python
C:/Users/francesco.cardia/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/francesco.cardia/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.0\bin\python36.zip
C:\PROGRA~1\QGIS3~1.0\apps\Python36\DLLs
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib
C:\Program Files\QGIS 3.0\bin
C:\PROGRA~1\QGIS3~1.0\apps\Python36
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages\Pythonwin
C:/Users/francesco.cardia/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by bstroebl** [comment]
Hi,
the released Plugin has hot been ported to QGIS 3. You may however try the _develop_ branch which includes all efforts for QGIS 3

**Comment by Francescocardia** [comment]
Hi Bernhard,
Thank you for your email.Hope the updated version will be released soon.I am a newbie, what is the develop branch?Thank you
F.
-------- Original message --------From: Bernhard Ströbl <notifications@github.com> Date: 14/05/2018  08:38  (GMT+01:00) To: bstroebl/DigitizingTools <DigitizingTools@noreply.github.com> Cc: Francescocardia <francescocardia67@gmail.com>, Author <author@noreply.github.com> Subject: Re: [bstroebl/DigitizingTools] DigitizingTools not working for QGIS 3.0.2 Girona (#26) 
Hi,

the released Plugin has hot been ported to QGIS 3. You may however try the develop branch which includes all efforts for QGIS 3

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bstroebl/DigitizingTools","title":"bstroebl/DigitizingTools","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bstroebl/DigitizingTools"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bstroebl in #26: Hi,\r\nthe released Plugin has hot been ported to QGIS 3. You may however try the _develop_ branch which includes all efforts for QGIS 3"}],"action":{"name":"View Issue","url":"https://github.com/bstroebl/DigitizingTools/issues/26#issuecomment-388711864"}}}
{"@type":"MessageCard","@context":"http://schema.org/extensions","hideOriginalBody":"false","originator":"37567f93-e2a7-4e2a-ad37-a9160fc62647","title":"Re: [bstroebl/DigitizingTools] DigitizingTools not working for QGIS 3.0.2 Girona (#26)","sections":[{"text":"","activityTitle":"**Bernhard Ströbl**","activityImage":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","activitySubtitle":"@bstroebl","facts":[]}],"potentialAction":[{"name":"Add a comment","@type":"ActionCard","inputs":[{"isMultiLine":true,"@type":"TextInput","id":"IssueComment","isRequired":false}],"actions":[{"name":"Comment","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueComment\",\"repositoryFullName\":\"bstroebl/DigitizingTools\",\"issueId\":26,\"IssueComment\":\"{{IssueComment.value}}\"}"}]},{"name":"Close issue","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"IssueClose\",\"repositoryFullName\":\"bstroebl/DigitizingTools\",\"issueId\":26}"},{"targets":[{"os":"default","uri":"https://github.com/bstroebl/DigitizingTools/issues/26#issuecomment-388711864"}],"@type":"OpenUri","name":"View on GitHub"},{"name":"Unsubscribe","@type":"HttpPOST","target":"https://api.github.com","body":"{\"commandName\":\"MuteNotification\",\"threadId\":333983616}"}],"themeColor":"26292E"}

**Comment by bstroebl** [comment]
I provided a new version for QGIS 3 on the repo, please install and try
