### ISSUE TITLE
Snapping Issue with Split Features Tool

### ISSUE THREAD

**Issue by andywicht** [bstroebl/DigitizingTools#27]
I am observing an issue where the startpoint of the rubberband which is used to digitize the blade geometry is snapped to a nearby (not necessary the closest) vertex when defininig the startpoint of the blade geometry.

This only appears when snapping is activated:
- mode: to vertex
- tolerance: 10 pixels
- avoid intersections: true
- enable topological editing: true

Windows 10
QGIS 2.18.18 + QGIS 2.18.19

**Comment by bstroebl** [comment]
Hi Andy,
I cannot reporduce this issue here (Win7, QGIS 2.18.19). When you start digitizing the blade possible snap points are highlighted (one at a time) and if you left click the first point of the blade is snapped to the highlighted snap point.
Could you provide sample data and where in the data the problem arises?

**Comment by andywicht** [comment]
Hi Bernd,

as you can see in the gif, the snapping happens without the vertices being highlighted (outside of 10px tolerace). Here is the [sample.zip](https://github.com/bstroebl/DigitizingTools/files/2012575/sample.zip) I used. This behaviour also appears on a different machine. And it appears with any polygon shapefile or postgis layer I open.
I can't reproduce this behaviour with e.g. the native Split Parts tool (Advanced Digitizing Toolbar)

![snapping](https://user-images.githubusercontent.com/21099522/40169611-a9370f88-59c6-11e8-8298-a3eaceb73b57.gif)

**Comment by bstroebl** [comment]
Ok, I understand the problem, however if I click that far away from the polygon the first click point is not snapped; it is snapped if I come pretty close to the polygon, though (snap point not highlighted)
Just to be sure: are you using Version 0.11.5 of the plugin?
BTW the built-in function and this tool do not have any code in common so it is possible (though not desirable) that they behave differently

**Comment by andywicht** [comment]
Exactly. You describe the expected behaviour. 
The plugin version is 0.11.5 in both QGIS installations/both machines.

Let me know if I can test something more to figure out the cause of the issue.

**Comment by bstroebl** [comment]
fixed; new version of the plugin is available in the plugin repo

**Comment by andywicht** [comment]
confirmed! Thank you for fixing so quickly
