### ISSUE TITLE
Transform "Cut with polygon from another layer" to "update" tool

### ISSUE THREAD

**Issue by diomitri** [bstroebl/DigitizingTools#34]
A useful tool in GIS is, when editing a polygon layer, to be able to update polygons with polygons from other layers, in a topologically correct way. Copy/paste adds the new polygons over the existing. The tool "Cut with polygon from another layer" already does half the job, we just need to copy/paste the cutter layer's polygons to the gap created (proposed name: update with polygon from another layer"

**Comment by bstroebl** [comment]
Hi,
good idea! Would you think of a separate tool or an enhancement of the current tool (i.e. an option; either copy or not)?
