### ISSUE TITLE
Add a "pause" function to "Split features" tool

### ISSUE THREAD

**Issue by diomitri** [bstroebl/DigitizingTools#35]
"Split features" tool already exists in the core Advanced Digitizing Toolbar (though with different icon), so perhaps we should provide some extra functionalities, as compared to original tool:
1. "Split features" tool should behave as "Fill ring" tool, in case of when drawing a splitting line, the line closes to itself
2. When we need to split a complex part of the polygon, we have to draw a consecutive polyline that will split polygons we do not want to split. A 'pause' functionality (under a shortcut) should be added to be able to draw line parts between existing polygons
Both functionalities already exist in ArcGIS (Cut polygon tool)

**Comment by bstroebl** [comment]
DigitizingTools does not double any core functionality, see the [documentation](https://github.com/bstroebl/DigitizingTools/wiki/Usage) on _Split features_.
As to your proposals: I do not know current ArcGIS, so you should elaborate them a bit. AFAIU proposal 1 is covered by core's _fill ring_ tool, whereas I do not see the point in proposal 2. If you select a feature, only this feature is split, so there is no chance to split polygons you do not want to split.
