### ISSUE TITLE
Transform polygon to target area does not working

### ISSUE THREAD

**Issue by freeconst** [bstroebl/DigitizingTools#38]
QGIS 3.2.0-Bonn;
Digitizing Tools 1.1.4.

Python error when trying move polygon side/node:
`2018-07-13T08:19:45     WARNING    Traceback (most recent call last):
              File "/home/const/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DigitizingTools/tools/dtmovesidebyarea.py", line 141, in moveSide
              touch_p1_p2 = self.selected_feature.geometry().touches(QgsGeometry.fromPolyline([self.p1, self.p2]))
             TypeError: index 0 has type 'QgsPointXY' but 'QgsPoint' is expected`

**Comment by bstroebl** [comment]
Fixed in Version 1.1.5
