### ISSUE TITLE
LineStringZM not supported

### ISSUE THREAD

**Issue by Robyn873** [bstroebl/DigitizingTools#40]
Hello,

I am trying to flip certain lines within my saved polyline shapefile in QGIS 3.2.2. However when I select the line and attempt to flip it the digitizing tools (this plug in only) are greyed out. I tried editing and selecting a point file and it isn't greyed out but it is with my polylines. Any advice on how to fix?

**Comment by bstroebl** [comment]
Hard to tell from here. Can you share the shape file in question (or at least part of it)?

**Comment by Robyn873** [comment]
[Municipal System Storm.zip](https://github.com/bstroebl/DigitizingTools/files/2314242/Municipal.System.Storm.zip)

**Comment by bstroebl** [comment]
The Layer is a LineStringZM-Layer. This is currently not included in the list of allowed geometry types (mainly because I never faced it before). Convert it to a regular linestring and you are ready to go.

**Comment by Robyn873** [comment]
Thank you, it worked !
