### ISSUE TITLE
missing toolbar icons

### ISSUE THREAD

**Issue by szeemi** [bstroebl/DigitizingTools#41]
splitting by line button missing (mac)
![kepernyofoto 2018-09-27 - 12 39 07](https://user-images.githubusercontent.com/16690992/46140846-86d4cd00-c252-11e8-97ae-fc2b240fe8a8.png)

**Comment by szeemi** [comment]
Sorry,

Still no show in Qgis 3.2. What am I missing?
<img width="830" alt="kepernyofoto 2018-09-27 - 16 07 33" src="https://user-images.githubusercontent.com/16690992/46151652-88f95480-c26f-11e8-901d-923a009fb28f.png">

**Comment by szeemi** [comment]
OK, I think I get it now. Qgis crashes on install and the plugin is probably not active dispite of showing that it is installed, and this is the regular digitizing toolbar of qgis??
Now I'm trying to updte to 3.2.3. Maybe that will bring a solution.

**Comment by bstroebl** [comment]
Can we close this?

**Comment by szeemi** [comment]
sure, thx
