### ISSUE TITLE
"fill ring with a new feature (interactive mode)" doesn't use  default values for attributes

### ISSUE THREAD

**Issue by Nswany** [bstroebl/DigitizingTools#42]
"fill ring with a new feature (interactive mode)" this instrument doesn't add existing default values to the attributes  of created new polygon.

**Comment by bstroebl** [comment]
I cannot reproduce this using QGIS 3.4 and DigitizingTools 1.2.0. I have default values in PostGIS and set a default value in the form editor, both are applied. Please try if the default values are set when adding a new feature with QGIS' add-feature tool. If yes please describe what you are doing and/or provide sample data and a sample project. If no there must be something wrong with the default values' definition.

**Comment by bstroebl** [comment]
I this still valid?

**Comment by bstroebl** [comment]
closed due to lack of feedback
