### ISSUE TITLE
Plugin not working with PostGIS Layer

### ISSUE THREAD

**Issue by ralfWessels** [bstroebl/DigitizingTools#44]
When I start editing a PostGIS Layer all the Plugin tools remaining grey. When I save the Layer as Shapefile editing with the Plugin is possible.
I use QGIS 3.4.9-Madeira and PostgreSQL-Client-Version 9.2.4 / PostGIS 2.5.2

**Comment by bstroebl** [comment]
Hi Ralf,
strange thing because I am working with PostGIS layers all the time. What geometry type are the layers in question?
P.S. sorry for the late reply, you should have assigned this ticket to me.

**Comment by ralfWessels** [comment]
hi Bernhard,
thanks for reply, but meanwhile I use more up-to-date versions (specially PostgreSQL) and I have no more problems to use Plugin tools (e.g. Digitizing Tools) to edit my PostGIS-layers.

**Comment by bstroebl** [comment]
ok, good to know, thanks for feeback
