### ISSUE TITLE
Missing Icons 

### ISSUE THREAD

**Issue by arudolph10** [bstroebl/DigitizingTools#48]
QGIS 3.8.2
Digitizing Tools 1.4.1

I am missing the icons that allow you to split or cut with features from another layer
![icons](https://user-images.githubusercontent.com/26419039/64043343-6592f580-cb21-11e9-900f-66ce02b12b9b.jpg)

**Comment by bstroebl** [comment]
Please see [the wiki](https://github.com/bstroebl/DigitizingTools/wiki/Usage) and #47

**Comment by bstroebl** [comment]
Tools have been rekindled in version 1.5.0, see wiki for usage
