### ISSUE TITLE
Highlighted features do not clear

### ISSUE THREAD

**Issue by andywicht** [bstroebl/DigitizingTools#51]
When splitting or merging features the split off parts or remaining features are highlighted. Since a recent update (might have been 3.4.12 / 3.10.0) the highlight is not removed when highlighting another feature. The functions still work, but in order to clear the highlights QGIS has to be restarted.

Highlighting otherwise works fine (also with the QGIS core function "Merge Selected Features").

I tried to identify the problem, but didn't come far.  It look like some behavior in the underlying functions changed.

**Comment by bstroebl** [comment]
Fixed, please try latest version 1.5.1

**Comment by andywicht** [comment]
Fix confirmed! Thank you
