### ISSUE TITLE
Digitizing tools: Possibility of working on imperfect geometries.

### ISSUE THREAD

**Issue by xsaiama** [bstroebl/DigitizingTools#56]
Hi,
I want to use Digitizing tools on a file with errors to FIX it. It is absolutely necessary that Digitizing tools MIGHT work on imperfect files because it is too limiting.

**Comment by bstroebl** [comment]
I am sorry your description is too vague to give an answer. Can you please describe what you are doing and what is happening. Could you share the geometry in question? Why are you not fixing the errors in a first step using QGIS' standard tool set?

**Comment by xsaiama** [comment]
Hi Mr Ströbl.

Here is the message that Qgis gives me when I try an operation with Digitizing tools:

New geometry: Geometry's type is not compatible with the following layer: projet_stationnement. Fix geometries before commiting changes.

Digitizing tools would be much more useful if it were less selective on the quality of the data because they often come from external sources and are stored in the PostGis database We have to produce a result quickly, even if it means correcting the files later.
Very often, Qgis geoprocessing tools create the result in a new file rather than modifying the source file. Which is a waste of time and very inconvenient management when working in a database. That's why I dream of a tool that directly edits the file without fuss.


Regards,
________________________________
Marc-André Saia
Cartographe – Direction générale

Communauté métropolitaine de Montréal
1002, rue Sherbrooke Ouest, bureau 2400
Montréal (Québec) H3A 3L6
***@***.***D72156.B633EF80] (514) 350-2583
***@***.***D72156.B633EF80] (514) 350-2599

AVIS DE CONFIDENTIALITÉ
Ce courriel est strictement réservé à l'usage de la personne à qui il est destiné et peut contenir de l'information privilégiée ou confidentielle. Si vous avez reçu ce courriel par erreur, veuillez nous en aviser immédiatement et le supprimer de votre système informatique sans en tirer de copies.
Avant d'imprimer, pensez à l'environnement ! ***@***.***D72156.B633EF80]

De : Bernhard Ströbl ***@***.***>
Envoyé : 25 mars 2021 01:49
À : bstroebl/DigitizingTools ***@***.***>
Cc : Marc-André Saïa ***@***.***>; Author ***@***.***>
Objet : Re: [bstroebl/DigitizingTools] Digitizing tools: Possibility of working on imperfect geometries. (#56)


I am sorry your description is too vague to give an answer. Can you please describe what you are doing and what is happening. Could you share the geometry in question? Why are you not fixing the errors in a first step using QGIS' standard tool set?

**Comment by bstroebl** [comment]
The message indicates that the geometry type does not match the layer type, e.g. that you are trying to insert a line into a polygon layer. The hint asks you to fix that before committing (because committing in the current state would result in errors from the data provider). So to me it seems this is not a question of data quality but a question of inadequate results. Which tool are you using?

Are you aware of processing's "Edit features in place" tool that lets you change the features in the editable layer?

**Comment by xsaiama** [comment]
Hi Mr. Ströbl.

I want to use the "Cut with polugon" tool on a postgis polygon file. (There are no lines in there but polugons created by analysis of aerial images. There are necessarily polygons with self-intersections, therefore imperfect.



***@***.***D72221.35A749E0]

________________________________
Marc-André Saia
Cartographe – Direction générale

Communauté métropolitaine de Montréal
1002, rue Sherbrooke Ouest, bureau 2400
Montréal (Québec) H3A 3L6
***@***.***D72220.3EB5AAF0] (514) 350-2583
***@***.***D72220.3EB5AAF0] (514) 350-2599

AVIS DE CONFIDENTIALITÉ
Ce courriel est strictement réservé à l'usage de la personne à qui il est destiné et peut contenir de l'information privilégiée ou confidentielle. Si vous avez reçu ce courriel par erreur, veuillez nous en aviser immédiatement et le supprimer de votre système informatique sans en tirer de copies.
Avant d'imprimer, pensez à l'environnement ! ***@***.***D72220.3EB5AAF0]

De : Bernhard Ströbl ***@***.***>
Envoyé : 26 mars 2021 07:53
À : bstroebl/DigitizingTools ***@***.***>
Cc : Marc-André Saïa ***@***.***>; Author ***@***.***>
Objet : Re: [bstroebl/DigitizingTools] Digitizing tools: Possibility of working on imperfect geometries. (#56)


The message indicates that the geometry type does not match the layer type, e.g. that you are trying to insert a line into a polygon layer. The hint asks you to fix that before committing (because committing in the current state would result in errors from the data provider). So to me it seems this is not a question of data quality but a question of inadequate results. Which tool are you using?

Are you aware of processing's "Edit features in place" tool that lets you change the features in the editable layer?

**Comment by bstroebl** [comment]
as I wrote. This is not a question of geometries being imperfect but of the polygon resulting from the cutting process being the wrong geometry type for the layer. Check what type the resulting geometry is (the message is a warning, not an error so there must be a result). Check what geometry type the layer in question is and compare.

**Comment by xsaiama** [comment]
Hi!

It is working.

Thank you.

________________________________
Marc-André Saia
Cartographe – Direction générale

Communauté métropolitaine de Montréal
1002, rue Sherbrooke Ouest, bureau 2400
Montréal (Québec) H3A 3L6
***@***.***D72228.531832D0] (514) 350-2583
***@***.***D72228.531832D0] (514) 350-2599

AVIS DE CONFIDENTIALITÉ
Ce courriel est strictement réservé à l'usage de la personne à qui il est destiné et peut contenir de l'information privilégiée ou confidentielle. Si vous avez reçu ce courriel par erreur, veuillez nous en aviser immédiatement et le supprimer de votre système informatique sans en tirer de copies.
Avant d'imprimer, pensez à l'environnement ! ***@***.***D72228.531832D0]

De : Bernhard Ströbl ***@***.***>
Envoyé : 26 mars 2021 10:05
À : bstroebl/DigitizingTools ***@***.***>
Cc : Marc-André Saïa ***@***.***>; Author ***@***.***>
Objet : Re: [bstroebl/DigitizingTools] Digitizing tools: Possibility of working on imperfect geometries. (#56)


as I wrote. This is not a question of geometries being imperfect but of the polygon resulting from the cutting process being the wrong geometry type for the layer. Check what type the resulting geometry is (the message is a warning, not an error so there must be a result). Check what geometry type the layer in question is and compare.
