### ISSUE TITLE
Customizable angle snapping intervals

### ISSUE THREAD

**Issue by beyhh** [bstroebl/DigitizingTools#59]
I love the snapping to common angles feature but unfortunately, the smallest interval is 5°. 
Would it be possible to allow the user to create custom intervals? I my case, I would frequently require a 1° interval and sometimes even a 0.5° interval. 
Could this be achieved by manipulating a .py file somewhere?

**Comment by bstroebl** [comment]
This is the bug tracker for the DigitizingTools plugin; requests for improvements of QGIS' core features should be addressed to the QGIS bug tracker. I doubt you can achieve this by manipulating Python files as core is coded in C++.
Sorry that I cannot offer more help.

**Comment by beyhh** [comment]
Ok, thanks for the feedback. I obviously confused the Digitizing Tools Plugin (hence my hope for manipulating a py file) with the QGIS built-in Advanced Digitizing tools functionality.
